export const red = 'rgb(196,57,42)'
export const green = 'rgb(55,125,34)'
// Color Palette https://www.materialpalette.com/indigo/green
export const darkPrimaryColor    = '#303F9F'
export const defaultPrimaryColor = '#3F51B5'
export const lightPrimaryColor   = '#C5CAE9'
export const textPrimaryColor    = '#FFFFFF'
export const accentColor         = '#4CAF50'
export const primaryTextColor    = '#212121'
export const secondaryTextColor  = '#757575'
export const dividerColor        = '#BDBDBD'